import "./globals.css";
import { Montserrat } from 'next/font/google'; // 1. IMPORT FONT

// 2. INISIALISASI FONT
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // Sesuaikan weight yang Anda butuhkan
});

// Best practice: Pindahkan title ke metadata object
export const metadata = {
  title: 'M-Knows',
  description: 'Generated by create next app', // Ganti dengan deskripsi Anda
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head> tidak lagi diperlukan di sini, Next.js akan mengaturnya dari metadata */}
      
      {/* 3. TERAPKAN FONT KE <body> */}
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}